### ISSUE TITLE
updates with depandabot

### ISSUE THREAD

**Issue by hagenstrahl** [hagenstrahl/next-starter#20]
See https://docs.github.com/en/code-security/supply-chain-security/enabling-and-disabling-version-updates

```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
```
